// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1066_Giurgiteanu_Mihai_Andrei;

namespace _1066_Giurgiteanu_Mihai_Andrei.Migrations.Good
{
    [DbContext(typeof(ContractContext))]
    [Migration("20220504161140_GoodMigration")]
    partial class GoodMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("_1066_Giurgiteanu_Mihai_Andrei.Entities.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nameGood")
                        .HasColumnType("TEXT");

                    b.Property<int>("pricePerGood")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
